# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Numero de serie')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('street', models.CharField(max_length=100, verbose_name='Endereco')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('default_price', models.FloatField(verbose_name='Preco padrao')),
                ('per_hour_price', models.FloatField(verbose_name='Preco por hora')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Livre'), ('leased', 'Alugado'), ('occupied', 'Ocupado'), ('broken', 'Quebrado')], max_length=20)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingLot')),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpace'),
        ),
    ]
