# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
    ]
