# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(choices=[('idle', 'Livre'), ('leased', 'Alugado'), ('occupied', 'Ocupado'), ('broken', 'Quebrado')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de termino'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(blank=True, verbose_name='Data de inicio'),
        ),
    ]
