# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Codigo PIN'),
        ),
    ]
