# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20160824_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpace'),
        ),
    ]
