# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rental_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 8, 15, 32, 39, 901203, tzinfo=utc), verbose_name='Ultima atualizacao'),
            preserve_default=False,
        ),
    ]
