# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20160826_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_status',
            field=models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado'), ('paid', 'Pago')], max_length=50, verbose_name='Status da locacao'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('space', 'Aluguel de vaga'), ('bicycle', 'Aluguel de bicicleta')], max_length=50, verbose_name='Tipo de locacao'),
        ),
    ]
