# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20160826_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('open', 'Aberto'), ('closed', 'Fechado'), ('paid', 'Pago')], max_length=50, verbose_name='Status da locacao'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateField(blank=True, verbose_name='Data de inicio'),
        ),
    ]
