# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20160913_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
