# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20160824_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao'),
        ),
    ]
