# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20160826_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
