# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20160913_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=50, verbose_name='Total'),
        ),
    ]
