# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20160913_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=50, null=True, verbose_name='Total'),
        ),
    ]
