# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_rental_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.FloatField(blank=True, verbose_name='Total'),
        ),
    ]
