# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='parking.ParkingLot'),
        ),
    ]
