# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20160826_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('confirmed', 'Confirmado'), ('refused', 'Cancelado')], default='open', max_length=50),
        ),
    ]
