# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20160913_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Preco padrao'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='per_hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Preco por hora'),
        ),
    ]
