# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20160826_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='number',
        ),
    ]
